// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef webeditor_h
#define webeditor_h
#include <FL/Fl.H>
void upload(); 
void list(); 
void delete_(); 
void preview(); 
void edit(); 
void create(); 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *file_browser;
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *text_editor;
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
extern Fl_Output *filename_output;
#include <FL/Fl_Help_View.H>
extern Fl_Help_View *html_view;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *source_view;
#include <FL/Fl_Input.H>
extern Fl_Input *server_input;
extern Fl_Input *user_input;
extern Fl_Input *password_input;
Fl_Double_Window* make_window();
#endif
