// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gtdwindow_h
#define gtdwindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *sections;
extern Fl_Browser *items;
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *content;
Fl_Double_Window* make_window();
#endif
