// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "gtdwindow.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(556, 370);
    w = o; if (w) {/* empty */}
    { new Fl_Browser(0, 0, 140, 370);
    } // Fl_Browser* o
    { new Fl_Browser(140, 0, 415, 140);
    } // Fl_Browser* o
    { new Fl_Text_Editor(140, 140, 415, 230);
    } // Fl_Text_Editor* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
