// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "gtdwindow.h"

Fl_Browser *sections=(Fl_Browser *)0;

Fl_Browser *items=(Fl_Browser *)0;

Fl_Text_Editor *content=(Fl_Text_Editor *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(556, 370, "GTD Viewer");
    w = o; if (w) {/* empty */}
    { sections = new Fl_Browser(0, 0, 140, 370);
      sections->type(1);
    } // Fl_Browser* sections
    { items = new Fl_Browser(140, 0, 415, 140);
    } // Fl_Browser* items
    { content = new Fl_Text_Editor(140, 140, 415, 230);
    } // Fl_Text_Editor* content
    o->end();
  } // Fl_Double_Window* o
  return w;
}
