// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "picturequiz2.h"

static void cb_Start(Fl_Button*, void*) {
  start_session();
}

static void cb_Add(Fl_Button*, void*) {
  add_card();
}

Fl_Value_Output *cards_in_session=(Fl_Value_Output *)0;

Fl_Wizard *wizard=(Fl_Wizard *)0;

Fl_Box *image_box=(Fl_Box *)0;

Fl_Box *good_box=(Fl_Box *)0;

Fl_Group *bad_box=(Fl_Group *)0;

Fl_Box *answer_box=(Fl_Box *)0;

Fl_Box *session_over=(Fl_Box *)0;

static void cb_Go(Fl_Return_Button*, void*) {
  go();
}

Fl_Input *answer_input=(Fl_Input *)0;

Fl_Value_Output *session_nr=(Fl_Value_Output *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(555, 440);
    w = o; if (w) {/* empty */}
    { Fl_Button* o = new Fl_Button(0, 0, 105, 25, "Start Session");
      o->callback((Fl_Callback*)cb_Start);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(105, 0, 105, 25, "Add Card");
      o->callback((Fl_Callback*)cb_Add);
    } // Fl_Button* o
    { cards_in_session = new Fl_Value_Output(325, 0, 60, 25, "Cards in Session");
    } // Fl_Value_Output* cards_in_session
    { wizard = new Fl_Wizard(0, 25, 555, 390);
      { image_box = new Fl_Box(0, 25, 555, 390);
        image_box->hide();
      } // Fl_Box* image_box
      { good_box = new Fl_Box(0, 25, 555, 390, "Good");
        good_box->labelfont(1);
        good_box->labelsize(60);
        good_box->labelcolor((Fl_Color)61);
        good_box->hide();
      } // Fl_Box* good_box
      { bad_box = new Fl_Group(0, 25, 555, 390);
        { Fl_Box* o = new Fl_Box(0, 25, 555, 175, "Bad");
          o->labelfont(1);
          o->labelsize(60);
          o->labelcolor(FL_RED);
        } // Fl_Box* o
        { answer_box = new Fl_Box(0, 200, 555, 215);
          answer_box->labelfont(1);
          answer_box->labelsize(60);
        } // Fl_Box* answer_box
        bad_box->end();
      } // Fl_Group* bad_box
      { session_over = new Fl_Box(0, 25, 555, 390, "Session Over");
        session_over->labelfont(1);
        session_over->labelsize(60);
        session_over->hide();
      } // Fl_Box* session_over
      wizard->end();
      Fl_Group::current()->resizable(wizard);
    } // Fl_Wizard* wizard
    { Fl_Return_Button* o = new Fl_Return_Button(500, 415, 55, 25, "Go");
      o->callback((Fl_Callback*)cb_Go);
    } // Fl_Return_Button* o
    { answer_input = new Fl_Input(0, 415, 500, 25);
    } // Fl_Input* answer_input
    { session_nr = new Fl_Value_Output(490, 0, 60, 25, "Session Nr");
    } // Fl_Value_Output* session_nr
    o->end();
  } // Fl_Double_Window* o
  return w;
}
