// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef picturequiz_h
#define picturequiz_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
extern Fl_Box *question_box;
extern Fl_Box *image_box;
#include <FL/Fl_Input.H>
extern Fl_Input *answer_input;
#include <FL/Fl_Return_Button.H>
Fl_Double_Window* make_window();
void go(); 
#endif
