// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef picturequiz2_h
#define picturequiz2_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *cards_in_session;
#include <FL/Fl_Wizard.H>
extern Fl_Wizard *wizard;
#include <FL/Fl_Box.H>
extern Fl_Box *image_box;
extern Fl_Box *good_box;
#include <FL/Fl_Group.H>
extern Fl_Group *bad_box;
extern Fl_Box *answer_box;
extern Fl_Box *session_over;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Input.H>
extern Fl_Input *answer_input;
extern Fl_Value_Output *session_nr;
Fl_Double_Window* make_window();
void go(); 
void add_card(); 
void start_session(); 
#endif
