// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef picturequiz_h
#define picturequiz_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
extern Fl_Box *question_box;
#include <FL/Fl_Input.H>
extern Fl_Input *answer_input;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Wizard.H>
extern Fl_Wizard *wizard;
extern Fl_Box *image_box;
extern Fl_Box *good_box;
#include <FL/Fl_Group.H>
extern Fl_Group *bad_group;
extern Fl_Box *bad_box;
extern Fl_Box *solution_box;
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *bucket;
extern Fl_Value_Output *level_1;
extern Fl_Value_Output *level_2;
extern Fl_Value_Output *level_3;
extern Fl_Value_Output *level_4;
extern Fl_Value_Output *level_5;
extern Fl_Value_Output *session;
extern Fl_Value_Output *deck_current;
extern Fl_Value_Output *deck_retired;
extern Fl_Value_Output *deck_0;
extern Fl_Value_Output *deck_1;
extern Fl_Value_Output *deck_2;
extern Fl_Value_Output *deck_3;
extern Fl_Value_Output *deck_4;
extern Fl_Value_Output *deck_5;
extern Fl_Value_Output *deck_6;
extern Fl_Value_Output *deck_7;
extern Fl_Value_Output *deck_8;
extern Fl_Value_Output *deck_9;
Fl_Double_Window* make_window();
void go(); 
void mark_as_poor_card(); 
#endif
