// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "picturequiz.h"

Fl_Box *question_box=(Fl_Box *)0;

Fl_Box *image_box=(Fl_Box *)0;

Fl_Input *answer_input=(Fl_Input *)0;

static void cb_Go(Fl_Return_Button*, void*) {
  go();
}

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(660, 425);
    w = o; if (w) {/* empty */}
    { question_box = new Fl_Box(0, 0, 660, 40, "What is it?");
      question_box->box(FL_UP_BOX);
    } // Fl_Box* question_box
    { image_box = new Fl_Box(0, 40, 660, 360);
      image_box->box(FL_UP_BOX);
      Fl_Group::current()->resizable(image_box);
    } // Fl_Box* image_box
    { answer_input = new Fl_Input(0, 400, 590, 25);
    } // Fl_Input* answer_input
    { Fl_Return_Button* o = new Fl_Return_Button(590, 400, 70, 25, "Go!");
      o->callback((Fl_Callback*)cb_Go);
    } // Fl_Return_Button* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
